# Generated by Django 6.0.2 on 2026-04-02 21:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('patente', models.CharField(db_index=True, help_text='Identificador único del vehículo (Chile: patente).', max_length=20, unique=True)),
                ('presupuesto_reparacion', models.PositiveIntegerField(help_text='Monto estimado en pesos chilenos (CLP), sin decimales.', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_ingreso', models.DateField()),
                ('estado_reparacion', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('diagnostico', 'En diagnóstico'), ('reparacion', 'En reparación'), ('repuestos', 'Esperando repuestos'), ('listo', 'Listo para retiro'), ('entregado', 'Entregado')], db_index=True, default='pendiente', max_length=20)),
                ('notas_internas', models.TextField(blank=True)),
                ('propietario', models.ForeignKey(blank=True, help_text='Usuario cliente al que se asigna el vehículo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['-fecha_ingreso', 'patente'],
                'indexes': [models.Index(fields=['estado_reparacion', 'fecha_ingreso'], name='vehiculos_v_estado__521a15_idx')],
            },
        ),
    ]
